# Generated by Django 4.2.7 on 2023-11-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_recipe_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='youtube',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
