# Generated by Django 4.2.7 on 2023-11-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recipe_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='youtube',
        ),
    ]
